apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: oneapi
  namespace: {{ .Release.Namespace }}
spec:
  http:
  - name: oneapi-route
    match:
      paths:
      - /v1/models
      - /v1/embeddings
      - /v1/chat/*
    backends:
    - serviceName: {{ .Release.Name }}-oneapi
      servicePort: 3000
    plugins:
    - name: openid-connect
      enable: true
      config:
        client_id: {{ .Values.dex.config.staticClient.id | quote }}
        client_secret: {{ .Values.dex.config.staticClient.secret }}
        discovery:  {{ printf "%s/.well-known/openid-configuration" .Values.dex.config.issuer }}
        bearer_only: true
        set_userinfo_header: true
        set_id_token_header: false
        ssl_verify: false
    - name: limit-req
      enable: true
      config:
        rate: 300
        burst: 300
        rejected_code: 429
        key_type: var
        key: "$remote_addr $http_x_forwarded_for"
    - name: limit-count
      enable: true
      config:
        count: 10000
        rejected_code: 429
        time_window: 86400
        key: "$remote_addr $http_x_forwarded_for"
    - name: file-logger
      enable: true
      config:
        include_req_body: true
        include_resp_body: true
        path: logs/access.log
    - name: proxy-rewrite
      enable: true
      config:
        headers:
          Authorization: {{ printf "Bearer %s" .Values.oneapi.auth.rootToken }}