apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: login-vscode
  namespace: {{ .Release.Namespace | quote }}
spec:
  http:
  - name: login-vscode-route
    match:
      paths: 
        - /realms/*
        - /login/vscode
        - /login/oidc
    backends:
    - serviceName: {{ .Release.Name }}-oneapi
      servicePort: 3000
    plugins:
    - name: openid-connect
      enable: true
      config:
        bearer_only: false
        client_id: {{ .Values.dex.config.staticClient.id | quote }}
        client_secret: {{ .Values.dex.config.staticClient.secret }}
        discovery: {{ printf "%s/.well-known/openid-configuration" .Values.dex.config.issuer }}
        redirect_uri: 
        scope: "openid email profile"
        session:
          secret: "6c7a00e8e4c941b09bcb66d4aa81e7f"
        set_userinfo_header: false
        set_id_token_header: false
        set_access_token_header: true
        access_token_in_authorization_header: false
        renew_access_token_on_expiry: true
        refresh_session_interval: 900
        access_token_expires_leeway: 600
        ssl_verify: false
    - name: redirect
      enable: true
      config:
        uri:  "vscode://zgsm-ai.zgsm/callback?token=${http_x_access_token}"
        ret_code: 302
    - name: file-logger
      enable: true
      config:
        include_req_body: true
        include_resp_body: true
        path: logs/access.log