{{- if .Values.apisix.apisix.ssl.enabled }}
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: apisix-tls
  namespace: {{ .Release.Namespace | quote }}
spec:
  hosts:
    - {{ .Values.apisix.apisix.ssl.fallbackSNI | quote }}
  secret:
    name: apisix-tls-secret
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
