apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: dex
  namespace: {{ .Release.Namespace }}
spec:
  http:
  - name: dex-route
    match:
      paths:
      - /dex/*
    backends:
    - serviceName: {{ .Release.Name }}-dex
      servicePort: 5556
    plugins:
    - name: file-logger
      enable: true
      config:
        include_req_body: true
        include_resp_body: true
        path: logs/access.log