apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-snapshot-repository
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.elasticsearch.pvc.size | quote }}
  storageClassName: {{ .Values.elasticsearch.pvc.storageClassName | quote }}