apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.elasticsearch.security.existingSecret | quote }}
type: Opaque
data:
{{- if .Values.auth.elasticsearch.password }}
  elasticsearch-password: {{ .Values.auth.elasticsearch.password | b64enc | quote }}
{{- end }}