{{- if .Values.fauxpilot.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fauxpilot
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "zgsm-backend.name" . }}
    helm.sh/chart: {{ include "zgsm-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: fauxpilot
spec:
  replicas: {{ .Values.fauxpilot.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zgsm-backend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: fauxpilot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "zgsm-backend.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: fauxpilot
    spec:
      containers:
      - name: {{ .Chart.Name }}-fauxpilot
        image: "{{ .Values.fauxpilot.image.repository }}:{{ .Values.fauxpilot.image.tag | default "latest" }}"
        imagePullPolicy: {{ .Values.fauxpilot.image.pullPolicy | default "IfNotPresent" }}
        command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]
        env:
        {{- range $key, $value := .Values.fauxpilot.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        ports:
        - containerPort: 5000
          name: http
        resources:
          {{- toYaml .Values.fauxpilot.resources | nindent 12 }}
        #readinessProbe:
        #  httpGet:
        #    path: /healthz
        #    port: http
        #  initialDelaySeconds: 10
        #  periodSeconds: 30
        #  timeoutSeconds: 10
        #  failureThreshold: 3
        #livenessProbe:
        #  httpGet:
        #    path: /healthz
        #    port: http
        #  initialDelaySeconds: 30
        #  periodSeconds: 30
        #  timeoutSeconds: 10
        #  failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fauxpilot
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "zgsm-backend.name" . }}
    helm.sh/chart: {{ include "zgsm-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: fauxpilot
spec:
  type: {{ .Values.fauxpilot.service.type }}
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  selector:
    app.kubernetes.io/name: {{ include "zgsm-backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: fauxpilot
{{- end }} 
