apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.existingSecret | quote }}
type: Opaque
data:
{{- if .Values.auth.postgresql.password }}
  postgres-password: {{ .Values.auth.postgresql.password | b64enc | quote }}
  password: {{ .Values.auth.postgresql.password | b64enc | quote }}
  replication-password: {{ .Values.auth.postgresql.password | b64enc | quote }}
{{- end }}