apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgresql.primary.initdb.scriptsConfigMap }}
data:
  init_user_db.sql: |
    CREATE USER {{ .Values.auth.postgresql.username }} WITH PASSWORD '{{ .Values.auth.postgresql.password }}';
    {{- range .Values.auth.postgresql.databases }}
    CREATE DATABASE {{ . }} ENCODING 'UTF8';
    ALTER DATABASE {{ . }} OWNER TO {{ $.Values.auth.postgresql.username }};
    {{- end }}