# # # # # # # # # # # # # # # # # #
#       devBPM celery config       #
# # # # # # # # # # # # # # # # # #
---
common: &common
  # 指定 Broker
  broker_url: 'redis://redis:6379/7'
  # 指定 Backend
  result_backend: 'redis://redis:6379/8'
  # 指定时区，默认是 UTC
  timezone: 'Asia/Shanghai'
  # CELERY_TIMEZONE: 'UTC'
  # 并发 worker 数，不传默认为机器核数
  worker_concurrency: 20
  # 每个 woker 执行指定任务数后自行销毁,避免内存泄漏
  worker_max_tasks_per_child: 100
  # 某些情况下防止死锁
  force_execv: true
  CELERY_TASK_IGNORE_RESULT: true
  broker_connection_retry_on_startup: true

  # celery once的配置
  celery_once:
    url: 'redis://redis:6379/10'
    timeout: 3600

  imports:
    - tasks.beat_task
    - tasks.chat_task

development: &development
  <<: *common
  broker_url: 'redis://localhost:6379/7'
  result_backend: 'redis://localhost:6379/8'

staging: &staging
  <<: *common

test: &test
  <<: *common
  broker_url: 'redis://localhost:6379/7'
  result_backend: 'redis://localhost:6379/8'

production: &production
  <<: *common
