env: prod
server:
  listenAddr: ":8080"
cotun:
  addr: "cotun"
  timeout: 5
recycle:
  enable: false
  timeout: 180
  deadline: 3
storage: 
  cache: "/data"
port_range:
  start: 30000
  end: 31000