FROM docker.sangfor.com/containerd/python:3.10.10-slim-bullseye

ENV TIMEZONE=Asia/Shanghai

RUN sed -i 's/deb.debian.org/mirrors.sangfor.com/g' /etc/apt/sources.list \
    && sed -i 's|security.debian.org/debian-security|mirrors.sangfor.com/debian-security|g' /etc/apt/sources.list \
    && apt-get update \
    && apt install libpq-dev -y \
    && apt install --force-yes -y ca-certificates curl \
           build-essential gcc g++ \
           tzdata zip unzip vim wget \
           git openssh-client openssh-server zsh bash net-tools tmux sudo wget \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get install -y curl vim

RUN ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
