#!/usr/bin/env python
# -*- coding: utf-8 -*-
from third_platform.es.base_es import BaseESService

class UseCodeESService(BaseESService):
    """Record user feedback on the behavior of using code generated by LLM"""
    def __init__(self):
        super(UseCodeESService, self).__init__()
        self.index = "use_code"

use_code_es = UseCodeESService()
